### PR TITLE
2754 20 trying to apply a composite token that is a reference to another token fails if the referenced token comes from another set

### LINKED ISSUE #2754: 2.0: Trying to apply a composite token that is a reference to another token fails if the referenced token comes from another set
To reproduce:

- Create a typography token called `original` in a set called `A`.
- Create another typography token called `secondary` that references `{original}`.
- Create a set `B`
- In set `B` create a typography token called `tertiary` that references `{secondary}`
- Try to apply `tertiary` to a text layer
- Notice it does not do anything

On debugging it seems `resolvedValueWithReferences` is not set for those tokens when the reference comes from another set and is a reference to a typography token (and very likely also border / box shadow - any composite token that can reference another token)

https://github.com/tokens-studio/figma-plugin/assets/4548309/cec84a5c-b5e3-40fd-b63d-2477752cff7f

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin does not successfully affect token to figma if it has multiple level token references.

Closes #2754  

### What does this pull request do?
Added previous `resolvedValueWithReferences` to the token.

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/c8688223-48b6-4a0b-a330-b9baea542185

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/utils/TokenResolver.ts [hunk 1]
```diff
@@ -330,4 +331,4 @@ class TokenResolver {
 
 const defaultTokenResolver = new TokenResolver([]);
 
-export { defaultTokenResolver };
+export { defaultTokenResolver };
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/utils/TokenResolver.ts:334]: Linebreak

File: packages/tokens-studio-for-figma/src/utils/TokenResolver.ts [hunk 2]
```diff
@@ -187,6 +186,9 @@ class TokenResolver {
           newResolvedReferences.add(resolvedPath);
           // We initiate a new resolveReferences call, as we need to resolve the references of the reference
           const resolvedTokenValue = this.resolveReferences({ ...foundToken, name: resolvedPath } as SingleToken, newResolvedReferences);
+          if (resolvedTokenValue.resolvedValueWithReferences) {
+            resolvedValueWithReferences = resolvedTokenValue.resolvedValueWithReferences;
+          }
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/utils/TokenResolver.ts:191]: Can you add a test case that covers this

**Review by six7 — CHANGES_REQUESTED** [review]

**Review by six7 — APPROVED** [review]
🎉
