### PR TITLE
Fix resolved tokens preview in typo composition

### LINKED ISSUE #3019: Typography/Composition tokens don't give a good preview in the plugin, when using the W3C format
**Describe the bug**
The preview in the plugin shows a list of values, but not the same (good) view when using the old format.
The screenshots below show the W3C and legacy preview, where the legacy preview looks a lot better (with the resolved values).

**Screenshots or Screencasts**
W3C format
image

Legacy format
image

### PR DESCRIPTION
**Pull request by akshay-gupta7**
Resolves #3019

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/utils/is/isSingleBoxShadowToken.ts [hunk 1]
```diff
@@ -1,16 +1,30 @@
...
-export function isSingleBoxShadowToken(token: SingleToken | any): token is SingleBoxShadowToken {
+function getTokenTypeKey(ignoreTokenFormat: boolean): string {
+  const key = TokenFormat.tokenTypeKey;
+  return ignoreTokenFormat && key.startsWith('$') ? key.slice(1) : key;
+}
+
+function getTokenValueKey(ignoreTokenFormat: boolean): string {
+  const key = TokenFormat.tokenValueKey;
+  return ignoreTokenFormat && key.startsWith('$') ? key.slice(1) : key;
+}
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/utils/is/isSingleBoxShadowToken.ts:14]: You repeat this in all files - instead of duplicating logic, we should try to abstract the function.

Could you do that as a follow-up ? Approving this PR with the hope that this follow-up can be done 🙏

**Review by six7 — APPROVED** [review]
one comment that would be good to resolve as a followup

File: packages/tokens-studio-for-figma/src/utils/is/isSingleBoxShadowToken.ts (hunk 1 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/utils/is/isSingleBoxShadowToken.ts:14]: Raised a PR to address this as a follow-up #3034
