### PR TITLE
Fix double scroll in themes

### LINKED ISSUE #3006: Double scrolling in Themes modal
**Describe the bug**
Double scrolling in Themes modal: see video for clear

**To Reproduce**
1. Go to Manage Themes and edit a theme
2. Scroll in that window and go back to the overview of all themes
3. The other view is scrolled as well

**Screenshots or Screencasts**
<video src="https://github.com/user-attachments/assets/bc27bc5c-420e-4699-af7d-35c8d11ff765" />

### PR DESCRIPTION
**Pull request by akshay-gupta7**
Resolves #3006

### CODE REVIEW

**Review by macintoshhelper — APPROVED** [review]
LGTM

File: packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx [hunk 1]
```diff
@@ -151,6 +158,18 @@ export const ManageThemesModal: React.FC<React.PropsWithChildren<React.PropsWith
...
+    if (themeListRef.current) {
+      themeListRef.current.scrollTop = themeListScrollPosition;
+    }
+  }, [themeEditorOpen, themeListScrollPosition]);
+
+  const handleThemeListScroll = useCallback(() => {
+    if (themeListRef.current) {
+      setThemeListScrollPosition(themeListRef.current.scrollTop);
+    }
+  }, []);
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx:171]: Let's debounce this method, otherwise there's a chance that it'll get called many times [onScroll](https://github.com/tokens-studio/figma-plugin/pull/3027/files#diff-db0a813a6d988b1b509760080dbdac0d52ba0ffd7cece9997f9337673f352c83R240) 🙃 

Untested, but would something like this work?
```
const handleThemeListScrollDebounced = debounce(updateThemeListScrollPosition, 300);
```

Need to import from `lodash.debounce` and perhaps play around with the delay so it's not too slow!

Some inspiration ✨ https://hackernoon.com/eliminating-event-storms-with-debouncing-in-javascript

**Review by cuserox — CHANGES_REQUESTED** [review]
Nice work!

A small change to make the event listener safer when scrolling. Ensure to test out the times it renders and gets called properly 😄

File: packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx (hunk 1 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx:172]: Hey @cuserox, thanks for this suggestion, have implemented it! Do have a look!

File: packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx [hunk 2]
```diff
@@ -151,6 +159,20 @@ export const ManageThemesModal: React.FC<React.PropsWithChildren<React.PropsWith
...
+
+  const debouncedHandleThemeListScroll = useMemo(() => debounce(handleThemeListScroll, 200), [handleThemeListScroll]);
+
```
Comment (akshay-gupta7) [inline packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx:175]: used 200ms for now

**Review by cuserox — APPROVED** [review]
Good to go, debouncing for the win 💯
