### PR TITLE
2837 20 unable to create variable collections from sets

### LINKED ISSUE #2837: 2.0: Unable to create variable collections `From Sets`
Users cant create variable collections when creating variables with the `From Sets` tab.

To reproduce:

- Create a new file
- Create any token (e.g. color, line height)
- Go to Styles + Variables, click Export
- Make sure all Variables are selected
- Go to Confirm
- Click on Token Sets tab
- Click Export to Figma

Expected: variable collection is created
Actual: nothing is created

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin does not create local variable collections based on selected token sets. Because the `createNecessaryVariableCollections` function does not accept the parameter structure in case of selected sets.

Closes #2837  

### What does this pull request do?
Updated `createLocalVariablesWithoutModesInPlugin` function to send parameters with the structure which `createNecessaryVariableCollections` function can accept to proceed.

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/dbacb5e3-2141-4ae0-9996-153375506a9c

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts [hunk 1]
```diff
@@ -30,6 +30,18 @@ export default async function createLocalVariablesWithoutModesInPlugin(tokens: R
 
   const checkSetting = !settings.variablesBoolean && !settings.variablesColor && !settings.variablesNumber && !settings.variablesString;
   if (!checkSetting) {
+    const themesToCreateCollections = selectedSets.reduce((acc: ThemeObject[], curr: ExportTokenSet) => {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts:33]: would you not be able to re-use the `themeContainer` const on line 45 for this? I think thats what it was intended for?

File: packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts [hunk 2]
```diff
@@ -39,19 +51,16 @@ export default async function createLocalVariablesWithoutModesInPlugin(tokens: R
...
-        const setTokens: Record<string, AnyTokenList> = {
-          [set.set]: tokens[set.set],
-        };
         const { collection, modeId } = findCollectionAndModeIdForTheme(set.set, set.set, collections);
 
         if (!collection || !modeId) return;
 
         const allVariableObj = await updateVariables({
-          collection, mode: modeId, theme: themeContainer, tokens: setTokens, settings, filterByTokenSet: set.set,
+          collection, mode: modeId, theme: themeContainer, tokens, settings, filterByTokenSet: set.set,
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/plugin/createLocalVariablesWithoutModesInPlugin.ts:63]: I think this part here is whats causing an issue when multiple sets have the same tokens. For example, load up the Preset, and then activate each set. Try to create variables based on sets. Notice that the `light` set is going to be empty.

image

**Review by six7 — CHANGES_REQUESTED** [review]
