### PR TITLE
Fix plugin crashing when a huge token set is exported to variables

### LINKED ISSUE #3425: Plugin crashes when exporting variables from large token sets
**Describe the bug**
The plugin crashes when attempting to export a large token set to create variables in Figma. This seems to happen consistently when the token set is significantly large, potentially due to Figma's memory allocation limits which leads to abrupt crashes.

**To Reproduce**
- Open the plugin in a Figma file.
- Export a  large token set (e.g., 1000+ tokens).
- Plugin becomes unresponsive and/or crashes.

**Expected behavior**

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

### PR DESCRIPTION
**Pull request by akshay-gupta7**
### Why does this PR exist?

Closes #3425 
We are observing that when users are attempting to export sets with huge tokens, (typically >1000 atleast), the plugin is freezing and then crashing.
Error logs point to a memory leakage on Figma's end. This PR addresses our approach to handle such huge sets.

### What does this pull request do?

This PR changes the approach to manage such huge tokens in batches of 100, instead of processing all at one, if token count is above 1000.

### Testing this change

- Export a  large token set (e.g., 1000+ tokens).
- This should now display progress bar and the plugin shouldn't crash, due to the memory leakage issue

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts [hunk 1]
```diff
@@ -7,13 +7,100 @@ import { convertTokenTypeToVariableType } from '@/utils/convertTokenTypeToVariab
...
+  variablesInFigma: Variable[],
+  collection: VariableCollection,
+  mode: string,
+  baseFontSize: string,
+  shouldRename: boolean,
+  variableKeyMap: Record<string, string>,
+  referenceVariableCandidates: ReferenceVariableType[],
+  renamedVariableKeys: string[],
+) {
+  await Promise.all(batch.map(async (token) => {
```
Comment (jorenbroekema) [inline packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts]:
```suggestion
  return Promise.all(batch.map(async (token) => {
```
since we don't need to await for anything inside the scope of this function, we can just return it, which returns the Promise that's a result of Promise.all()

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts [hunk 2]
```diff
@@ -7,13 +7,100 @@ import { convertTokenTypeToVariableType } from '@/utils/convertTokenTypeToVariab
...
+    const variableType = convertTokenTypeToVariableType(token.type, token.value);
+    // If id matches the variableId, or name patches the token path, we can use it to update the variable instead of re-creating.
+    // This has the nasty side-effect that if font weight changes from string to number, it will not update the variable given we cannot change type.
+    // In that case, we should delete the variable and re-create it.
+    const variable = variablesInFigma.find((v) => (v.key === token.variableId && !v.remote) || v.name === token.path) || figma.variables.createVariable(token.path, collection, variableType);
```
Comment (jorenbroekema) [inline packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts]:
```suggestion
    const variable = variablesInFigma.find((v) => (v.key === token.variableId && !v.remote) || v.name === token.path) ?? figma.variables.createVariable(token.path, collection, variableType);
```
prefer nullish coalescing for fallbacks, so you don't end up using a fallback for a valid falsy value like 0 or ''

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts [hunk 3]
```diff
@@ -25,78 +112,84 @@ export default async function setValuesOnVariable(
...
+
+  // Process tokens in batches to prevent memory leaks with large token sets
+  // Use smaller batch sizes for very large token sets to prevent memory issues
+  const totalTokens = tokens.length;
+  let BATCH_SIZE = 100;
+  if (totalTokens > 10000) {
+    BATCH_SIZE = 50;
+  } else if (totalTokens > 5000) {
+    BATCH_SIZE = 75;
+  }
```
Comment (jorenbroekema) [inline packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts]:
```suggestion
  // clamp batch size between 100 and 50, for tiny sets -> 100, for sets>10000 -> 50
  const BATCH_SIZE = Math.round(Math.min(Math.max(100 - totalTokens / 200, 50), 100));
```

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts [hunk 4]
```diff
@@ -25,78 +112,84 @@ export default async function setValuesOnVariable(
...
+      }
+      tracker.reportIfNecessary();
+
+      // For very large token sets, add longer delays to prevent memory issues
+      if (i + BATCH_SIZE < totalTokens) {
+        let delay = 10;
+        if (totalTokens > 10000) {
+          delay = 50;
+        } else if (totalTokens > 5000) {
+          delay = 25;
```
Comment (jorenbroekema) [inline packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts]: Put this logic near the same LOC that contains the batch size logic. DELAY should be a constant just like BATCH_SIZE.
You can also use a clamp math function for this, see my other comment for an example. `totalTokens / 200`, rounded, clamped between 10 and 50.

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts [hunk 5]
```diff
@@ -25,78 +112,84 @@ export default async function setValuesOnVariable(
...
-    }));
+    }
+
+    postToUI({
+      type: MessageFromPluginTypes.COMPLETE_JOB,
+      name: BackgroundJobs.PLUGIN_UPDATEPLUGINDATA,
+    });
+
+    if (totalTokens > 1000) {
+      notifyUI(`Successfully processed ${totalTokens} tokens!`, { timeout: 2000 });
```
Comment (jorenbroekema) [inline packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts]: We don't notify for small tokensets? why not?

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts [hunk 6]
```diff
@@ -25,78 +112,75 @@ export default async function setValuesOnVariable(
...
-          referenceVariableCandidates.push({
-            variable,
-            modeId: mode,
-            referenceVariable: referenceTokenName,
-          });
-        }
+    for (let i = 0; i < totalTokens; i += BATCH_SIZE) {
+      const batch = tokens.slice(i, i + BATCH_SIZE);
+
+      await processBatch(
```
Comment (jorenbroekema) [inline packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts:143]: Would it still work if you parallelized this? Rather than 1 batch waiting for the previous batch to complete? Or does that defeat the purpose of this PR which is to actually sequence things in batches to avoid the memory issues?
Might be good to add a comment if so, so someone in the future doesn't parallelize this and cause a regression of the bug

**Review by jorenbroekema — APPROVED** [review]

File: packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts (hunk 6 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/plugin/setValuesOnVariable.ts:143]: sure, I will add that comment
