### PR TITLE
2962 unable to duplicate a token with the same name inside a set

### LINKED ISSUE #2962: Unable to duplicate a token with the same name inside a set
**Describe the bug**
Tokens nested in groups are unable to have the same name, even if creating a subgroup. [Original thread](https://hyma-team.slack.com/archives/C06RHB9RT2B/p1720024603584389)📝 

Probably related to the deduplication of tokens work: https://github.com/tokens-studio/figma-plugin/issues/2779

**To Reproduce**
1. Duplicate a token (i.e. `base-color`)
2. Name this token something containing what it references (i.e. `base-color.reference-test`)
3. Click create token
4. Token is not on the list _but_ was actually created

**Expected behavior**
The token should be on the list.

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin allows users to create a token group that shares a name with existing token.

Closes #2962  

### What does this pull request do?
Updated logic to prevent creating a token group that shares a name with existing token and updated error message to give more sense.

### Additional Notes (if any)

image

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx [hunk 1]
```diff
@@ -132,7 +132,7 @@ function EditTokenForm({ resolvedTokens }: Props) {
 
   const hasPriorTokenName = React.useMemo(() => {
     const tokensWithSameParent = resolvedTokens.filter((t) => t.internal__Parent === activeTokenSet);
-    if (internalEditToken?.status === EditTokenFormStatus.CREATE) {
+    if (internalEditToken.status && [EditTokenFormStatus.CREATE, EditTokenFormStatus.DUPLICATE].includes(internalEditToken.status)) {
```
Comment (macintoshhelper) [inline packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx:135]: Can do this I think, slightly more readable and should have the same null safety:

```tsx
if ([EditTokenFormStatus.CREATE, EditTokenFormStatus.DUPLICATE].includes(internalEditToken?.status)) {
```

Comment (macintoshhelper) [reply packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx]: Sorry, probably best to change this back, this breaks the build because of a TypeScript error:

```tsx
if (internalEditToken.status && [EditTokenFormStatus.CREATE, EditTokenFormStatus.DUPLICATE].includes(internalEditToken.status)) {
```

**Review by macintoshhelper — APPROVED** [review]
LGTM

**Review by six7 — APPROVED** [review]
