### PR TITLE
Fix/ when switching to input mode from a referenced Border token, all…

### LINKED ISSUE #2823: Overriding border token doesn’t reflect the values in the token
**Describe the bug**
When trying to override an existing border token with "input mode," the token does not accept the new values. As a result, we cannot update the border token as intended.

**To Reproduce**
1. Navigate to the plugin 
2. create a border token with respected values ex: `border.sm`
3. now create another border token ex: `border.card` referring to the border.sm 
4. now edit the `border.card`, switch to input mode, and try to change the values and see the error.

**Expected behavior**
When trying to override an existing border token with "input mode," the token should accept the new values. As a result, we should be able to update the border token as intended.

**Screenshots or Screencasts**

https://github.com/tokens-studio/figma-plugin/assets/140593995/bfa8c6a7-92b8-4361-a70f-6aa49dea5a81

**Figma file (optional)**
[Test File
](https://www.figma.com/design/1KfJpbGnUYs41XzUsuRpG1/Untitled?node-id=1-5&t=ozDDmUNUNKw3XhS2-1)

### PR DESCRIPTION
**Pull request by akshay-gupta7**
Fixes #2823 

- When a user will switch to input mode from a border token which already points to a reference, the fields color, width and stroke style shall be pre-populated with the referenced values and the user will be able to choose values to override them

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx [hunk 1]
```diff
@@ -265,14 +277,29 @@ function EditTokenForm({ resolvedTokens }: Props) {
...
+    (newBorderValue: SingleBorderToken['value']) => {
+      if (internalEditToken?.type === TokenTypes.BORDER && typeof newBorderValue === 'object') {
+        setInternalEditToken({
+          ...internalEditToken,
+          value: { ...newBorderValue },
+        });
+      }
+    },
+    [internalEditToken],
+  );
```
Comment (akshay-gupta7) [inline packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx:302]: This is the relevant part of the change in this file, I ran prettier command before committing which made lots of formatting changes

File: packages/tokens-studio-for-figma/src/app/components/BorderTokenForm.tsx [hunk 2]
```diff
@@ -36,61 +37,65 @@ export default function BorderTokenForm({
...
+            icon={<LinkBreak2Icon />}
+          />
+        )}
       </Stack>
-      {(mode === 'input' && internalEditToken.schema.schemas.value.type === 'object') ? (
+      {mode === 'input' && internalEditToken.schema.schemas.value.type === 'object' ? (
         <Stack gap={2} direction="column">
           {Object.entries(internalEditToken.schema.schemas.value.properties ?? {}).map(([key], keyIndex) => (
-            <>
+            <React.Fragment key={`border-input-fragment-${seed(keyIndex)}`}>
```
Comment (akshay-gupta7) [inline packages/tokens-studio-for-figma/src/app/components/BorderTokenForm.tsx:98]: There was a react child unique key error, hence I replaced the blank fragment with a React Fragment(with a key)

File: packages/tokens-studio-for-figma/src/app/components/BorderTokenForm.tsx [hunk 3]
```diff
@@ -36,61 +37,65 @@ export default function BorderTokenForm({
...
   const handleMode = React.useCallback(() => {
-    const changeMode = (mode === 'input') ? 'alias' : 'input';
-    setMode(changeMode);
+    if (mode === 'alias' && typeof internalEditToken.value === 'string') {
+      setBorderValue(selectedToken?.rawValue ?? {});
+    }
+    setMode(mode === 'input' ? 'alias' : 'input');
     setAlias('');
-  }, [mode]);
+  }, [mode, selectedToken, internalEditToken, setBorderValue]);
```
Comment (akshay-gupta7) [inline packages/tokens-studio-for-figma/src/app/components/BorderTokenForm.tsx:73]: The pertinent change in this file. Lots of prettier formatting in this file as well
