### PR TITLE
2778 20 make sure rename token group and duplicate token group cannot share name with an existing token group

### LINKED ISSUE #2778: 2.0: Make sure `Rename token group` and `Duplicate token group` cannot share name with an existing token group
Right now when you right click a token group and you click Duplicate or Rename, we allow users to enter an existing token group's name. This should be strictly forbidden as it will lead to unintended side-effects. Just like when you edit a token name you cannot enter an existing token group name, we should make it so that for renaming or duplicating groups this is not possible.

To reproduce:
- Create a token with a name `foo.bar` and another token with a name `otherfoo.bar`
- Right click the group `foo` and click Duplicate.
- Enter `otherfoo`.

This should show a warning and disable the Submit input.

Same as for rename:
To reproduce:
- Create a token with a name `foo.bar` and another token with a name `otherfoo.bar`
- Right click the group `foo` and click Rename.
- Enter `otherfoo`.

This should show a warning and disable the Submit input.

https://github.com/tokens-studio/figma-plugin/assets/4548309/22646d84-396c-46d6-ad1d-a7ac31801433

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin allows users to rename or duplicate token groups even there is existing token group with the name that user wants to update.

Closes #2778  

### What does this pull request do?
Added a condition variable to check whether it can rename or duplicate the token group with user input data.

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/886e5b73-7841-4832-9716-34d850c0f068

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx [hunk 1]
```diff
@@ -37,6 +37,16 @@ export default function DuplicateTokenGroupModal({
     onClose();
   }, [duplicateGroup, oldName, newName, selectedTokenSets, type, onClose]);
 
+  const canDuplicate = React.useMemo(() => {
+    const isDuplicated = Object.entries(tokens).some(([tokenSetKey, tokenList]) => {
+      if (selectedTokenSets.includes(tokenSetKey)) {
+        return tokenList.some((token) => token.name.split('.').includes(newName));
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx:43]: this would fail now if i had a token name like `foo.bar.something` and i tried to rename another group to `bar`. 

check the logic for single tokens - should be something similar to `startsWith` instead.

File: packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx [hunk 2]
```diff
@@ -17,6 +19,14 @@ type Props = {
 export default function RenameTokenGroupModal({
   isOpen, newName, oldName, onClose, handleRenameTokenGroupSubmit, handleNewTokenGroupNameChange,
 }: Props) {
+  const tokens = useSelector(tokensSelector);
+  const activeTokenSet = useSelector(activeTokenSetSelector);
+
+  const canRename = React.useMemo(() => {
+    const isDuplicated = tokens[activeTokenSet].some((token) => token.name.split('.').includes(newName));
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx:26]: same comment with .includes - startsWith likely but check how its done for single tokens

File: packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx [hunk 3]
```diff
@@ -37,6 +37,16 @@ export default function DuplicateTokenGroupModal({
     onClose();
   }, [duplicateGroup, oldName, newName, selectedTokenSets, type, onClose]);
 
+  const canDuplicate = React.useMemo(() => {
+    const isDuplicated = Object.entries(tokens).some(([tokenSetKey, tokenList]) => {
+      if (selectedTokenSets.includes(tokenSetKey)) {
```
[the remark this answers is not in the document]
Comment (robinhoodie0823) [reply packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx:42]: The function duplicates tokens to `selectedTokenSets`. There is a dropdown menu which user can select token sets where the token group can be duplicated to.

File: packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx [hunk 4]
```diff
@@ -40,7 +41,7 @@ export default function DuplicateTokenGroupModal({
   const canDuplicate = React.useMemo(() => {
     const isDuplicated = Object.entries(tokens).some(([tokenSetKey, tokenList]) => {
       if (selectedTokenSets.includes(tokenSetKey)) {
-        return tokenList.some((token) => token.name.split('.').includes(newName));
+        return tokenList.some((token) => token.name.startsWith(`${newName}.`));
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.tsx:44]: i think this also needs to include logic so that a group cannot share the name with a token

File: packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx [hunk 5]
```diff
@@ -21,9 +23,10 @@ export default function RenameTokenGroupModal({
 }: Props) {
   const tokens = useSelector(tokensSelector);
   const activeTokenSet = useSelector(activeTokenSetSelector);
+  const { t } = useTranslation(['tokens']);
 
   const canRename = React.useMemo(() => {
-    const isDuplicated = tokens[activeTokenSet].some((token) => token.name.split('.').includes(newName));
+    const isDuplicated = tokens[activeTokenSet].some((token) => token.name.startsWith(`${newName}.`));
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx:29]: same here, should make sure it cannot share name with a token

File: packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json [hunk 6]
```diff
@@ -86,8 +86,10 @@
   },
   "duplicate": "Duplicate",
   "rename": "Rename",
+  "renameGroupError": "There is already exist token group with the name input",
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json:89]:
```suggestion
  "renameGroupError": "There's an existing token or group with that name",
```

File: packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json [hunk 7]
```diff
@@ -86,8 +86,10 @@
...
   "emptyGroups": "empty groups",
   "duplicateGroup": "Duplicate Group",
+  "duplicateGroupError": "There is already exist token group with the name input",
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json:92]:
```suggestion
  "duplicateGroupError": "There's an existing token or group with that name",
```

**Review by six7 — CHANGES_REQUESTED** [review]
thanks for the updates! I'd still like to see a test added for this 🙏

File: packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.test.tsx [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+          newName="newName"
+          oldName="oldName"
+          onClose={() => {}}
+          handleNewTokenGroupNameChange={() => {}}
+        />
+      </Provider>
+    );
+  });
+
+  it('should not allow duplication when there are no duplicates', () => {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.test.tsx:41]:
```suggestion
  it('should disable duplication when there are duplicates', () => {
```

File: packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.test.tsx [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+        />
+      </Provider>
+    );
+
+    waitFor(async () => {
+      expect(getByText('duplicate')).toBeDisabled();
+    })
+  });
+
+  it('should allow duplication when there are duplicates', () => {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/DuplicateTokenGroupModal.test.tsx:63]:
```suggestion
  it('should not disable duplication when there are no duplicates', () => {
```

File: packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.test.tsx [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+          oldName="oldName"
+          onClose={() => {}}
+          handleRenameTokenGroupSubmit={() => {}}
+          handleNewTokenGroupNameChange={() => {}}
+        />
+      </Provider>
+    );
+  });
+
+  it('should not allow renaming when there are no duplicates', () => {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.test.tsx:41]:
```suggestion
  it('should disable renaming when there are duplicates', () => {
```

File: packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.test.tsx [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+        />
+      </Provider>
+    );
+
+    waitFor(async () => {
+      expect(getByText('Change')).toBeDisabled();
+    });
+  });
+
+  it('should allow renaming when there are duplicates', () => {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.test.tsx:63]:
```suggestion
  it('should not disable renaming when there are no duplicates', () => {
```

File: packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json [hunk 12]
```diff
@@ -86,8 +86,10 @@
   },
   "duplicate": "Duplicate",
   "rename": "Rename",
+  "renameGroupError": "There's an exist token or group with that name",
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json:89]:
```suggestion
  "renameGroupError": "There's an existing token or group with that name",
```

File: packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json [hunk 13]
```diff
@@ -86,8 +86,10 @@
...
   "emptyGroups": "empty groups",
   "duplicateGroup": "Duplicate Group",
+  "duplicateGroupError": "There's an exist token or group with that name",
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/i18n/lang/en/tokens.json:92]:
```suggestion
  "duplicateGroupError": "There's an existing token or group with that name",
```

File: packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx [hunk 14]
```diff
@@ -44,6 +57,7 @@ export default function RenameTokenGroupModal({
           autofocus
           required
         />
+        {!canRename && <ErrorMessage css={{ width: '100%' }}> {t('renameGroupError')} </ErrorMessage>}
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/modals/RenameTokenGroupModal.tsx:60]:
```suggestion
        {!canRename && <ErrorMessage css={{ width: '100%' }}>{t('renameGroupError')}</ErrorMessage>}
```

**Review by six7 — APPROVED** [review]
