### PR TITLE
Gitlab issue connecting to repo

### LINKED ISSUE #2339: Gitlab issue connecting to repo
**Describe the bug**
When trying to connect to a repo, there is some strange behaviour which is causing some issues to push/pull.

**To Reproduce**

- Multi-file sync to the root folder: this seems to work fine for pushing and pulling.
- Multi-file sync to a folder: when the folder already exists, it seems that a connection is established, but nothing happens. You're not able to push or pull.
- Multifile sync, where the folder needs to be created by the plugin: immediatly throws a 404 error.
- single file sync: initial push works, but pull gives a 404 error.

**Expected behavior**
Be able to push and pull without issues.

**Screenshots or Screencasts**
image
image

Internal slack issue link including screenrec: https://hyma-team.slack.com/archives/C03BSF3TADU/p1698407134836899

### PR DESCRIPTION
**Pull request by robinhoodie0823**
https://github.com/tokens-studio/figma-plugin/assets/103296157/80fcb735-5877-4991-846e-5bd150934e4e

Closes #2339

### CODE REVIEW

File: src/storage/GitlabTokenStorage.ts [hunk 1]
```diff
@@ -46,7 +46,11 @@ export class GitlabTokenStorage extends GitTokenStorage {
   }
 
   public async assignProjectId() {
-    const projects = await this.gitlabClient.Projects.search(this.repository, { membership: true });
+    const projects = await this.gitlabClient.Projects.all({
+      membership: true,
+      search: this.repository,
+      simple: true,
+    });
```
Comment (SorsOps) [inline src/storage/GitlabTokenStorage.ts:53]: We need a fix on the test file here for the mock as its no longer `@gitbeaker/browser` and now `@gitbeaker/rest`

**Review by SorsOps — CHANGES_REQUESTED** [review]

**Review by six7 — COMMENTED** [review]
Recent changes look good, but tests are failing still.

**Review by SorsOps — APPROVED** [review]
