### PR TITLE
2920 20 unable to import dtcg compatible tokens json file

### LINKED ISSUE #2920: 2.0 Unable to import DTCG compatible Tokens JSON file
**To Reproduce**
1. Go to Tokens Tab, Tools Icon->Load From File/Folder or preset
2. Choose file and import the file I attached or any other DTCG compatible file
3. There won't be any error, just that none of the tokens would be imported

Sample JSON I used
[New File 13 tokens (12).json](https://github.com/user-attachments/files/15973171/New.File.13.tokens.12.json)

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin is not flexible for DTCG format tokens in case of import tokens from files.

Closes #2920  

### What does this pull request do?
Updated validation schema of importing files to accept DTCG format tokens.

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/7716bec8-22f4-4be8-904a-4de92f682159

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/StorageItem.tsx [hunk 1]
```diff
@@ -34,12 +32,6 @@ const StorageItem = ({ item, onEdit }: Props) => {
   const { confirm } = useConfirm();
   const { setStorageType } = useStorage();
   const dispatch = useDispatch<Dispatch>();
-  const tokenFormat = useSelector(tokenFormatSelector);
-  const [isConvertModalOpen, setIsConvertModalOpen] = React.useState(false);
-
-  const openConvertModal = React.useCallback(() => {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/StorageItem.tsx:40]: Is this no longer needed or why was it removed?

File: packages/tokens-studio-for-figma/src/storage/schemas/singleTokenSchema.ts [hunk 2]
```diff
@@ -1,7 +1,15 @@
...
 
-export const singleTokenSchema = z.object({
+const baseSchema = z.object({
   value: z.any(),
   type: z.string(),
   description: z.string().optional(),
 }).passthrough();
+
+const dollarPrefixedSchema = z.object({
+  $value: z.any().optional(),
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/storage/schemas/singleTokenSchema.ts:10]: value is not optional

File: packages/tokens-studio-for-figma/src/app/components/StorageItem.tsx (hunk 1 above)
Comment (robinhoodie0823) [reply packages/tokens-studio-for-figma/src/app/components/StorageItem.tsx:40]: Yes. They are not used in the current files.

**Review by six7 — APPROVED** [review]
