### PR TITLE
2949 composition token input has wrong border radius value left

### LINKED ISSUE #2949: Composition token input has wrong border radius value left
We pass in `prefix` to some inputs to not have this border radius (e.g. look at how color tokens pass in that swatch, or in typography tokens).

But for composition tokens we show the wrong border radius

Image

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin has wrong border left radius of composite token input component.

Closes #2949  

### What does this pull request do?
Fix css of composite token input component to no radius

### Additional Notes (if any)

image

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/SingleCompositionTokenForm.tsx [hunk 1]
```diff
@@ -75,6 +75,29 @@ export default function SingleCompositionTokenForm({
...
   }, [onRemove, property]);
 
+  const renderSelect = () => (
+    <Select value={property || t('chooseAProperty')} onValueChange={onPropertySelected}>
+      <Select.Trigger
+        value={property || t('chooseAProperty')}
+        size="small"
+        css={{
+          borderTopRightRadius: '$0',
+          borderBottomRightRadius: '$0',
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/SingleCompositionTokenForm.tsx:85]:
```suggestion
          borderTopRightRadius: '0',
          borderBottomRightRadius: '0',
```

File: packages/tokens-studio-for-figma/src/app/components/Input.tsx [hunk 2]
```diff
@@ -138,6 +138,11 @@ const StyledPrefix = styled('div', {
         minWidth: '60px',
       },
     },
+    isComposition: {
+      true: {
+        padding: '0 0'
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/Input.tsx:143]:
```suggestion
        padding: '0'
```

Should suffice

**Review by cuserox — APPROVED** [review]
