### PR TITLE
fix: exporting and applying styles correctly references the tokens

### LINKED ISSUE #3049: Applying styles to selection shows resolved values instead of name references
Exported styles from the plugin to Figma look like so:
Screenshot 2024-08-06 at 13 34 07

## In production
**A. Exported all styles (no toggle options)**
✅ `1-color-token` shows as the fill when the color token :black_circle: is clicked
✅ `1-color-token` shows as the fill when the “Apply to selection” button is clicked

**B. Exported all styles (Prefix style with active theme name toggled)**
✅  `1-color-token` shows as the fill when the color token :black_circle: is clicked
✅  `1-color-token` shows as the fill when the “Apply to selection” button is clicked

**C. Exported all styles (Ignore first part of token name for styles toggled)**
✅  `1-color-token` shows as the fill when the color token :black_circle: is clicked
✅  `1-color-token` shows as the fill when the “Apply to selection” button is clicked

**D. Exported all styles (Prefix... & Ignore... toggled)**
✅  `1-color-token` shows as the fill when the color token :black_circle: is clicked
✅  `1-color-token` shows as the fill when the “Apply to selection” button is clicked

## In the V2 branch
When applying these to nodes, sometimes the reference is not the correct one.

**A. Exported all styles (no toggle options)**
✅ `1-color-token` shows as the fill when the color token :black_circle: is clicked
✅ `1-color-token` shows as the fill when the “Apply to selection” button is clicked

**B. Exported all styles (Prefix style with active theme name toggled)**
:x: `#FF00FF` shows as the fill when the color token :black_circle: is clicked
✅ `#FF00FF` shows as the fill when the “Apply to selection” button is clicked

**C. Exported all styles (Ignore first part of token name for styles toggled)**
:x: `1-color-token` shows as the fill when the color token :black_circle: is clicked
:x:  `#FF00FF` shows as the fill when the “Apply to selection” button is clicked

**D. Exported all styles (Prefix... & Ignore... toggled)**
:x:  `#FF00FF` shows as the fill when the color token :black_circle: is clicked
:x:  `#FF00FF` shows as the fill when the “Apply to selection” button is clicked

## Expectation
All styles applied should reference the name: _“If that setting is ON and the theme is active style should be applied if it can be found”_

🔨 Tested with [tokens.json](https://github.com/user-attachments/files/16510283/tokens.json)
✅ Style name reference
Screenshot 2024-08-06 at 13 33 58
:x: Resolved style value
Screenshot 2024-08-06 at 13 34 29

### PR DESCRIPTION
**Pull request by cuserox**
### Why does this PR exist?

Closes #3049

When users were exporting styles that had either **"Ignore first part of token name for styles"** or **"Prefix styles with active theme name"** toggled **ON**, the styles applied to the node would reference the _resolve value_ instead of the _token name_

Screenshot 2024-08-07 at 11 54 18

### What does this pull request do?
* Passes the correct props related to the toggle options onto the `TokenValueRetriever` 
* When "**Ignore first part...**" is toggled, the token at hand is only manipulated when its path length is over 1

### Testing this change
🔨 Tested with [tokens.json](https://github.com/user-attachments/files/16510283/tokens.json)
⏯️ Styles & Variables -> Export Styles & Variables -> Tick everything under **Styles** -> Select Themes / Token Sets (ensure there's at least 1 active one)

https://github.com/user-attachments/assets/edea2f82-f29e-40fd-9c31-69ddf20dbeac

#### A. No options toggled
✅ `1-color-token` shows as the fill when the color token ⚫ is clicked
✅ `1-color-token` shows as the fill when the “Apply to selection” button is clicked

#### B. Ignore first part...
✅ `1-color-token` shows as the fill when the color token ⚫ is clicked
✅ `1-color-token` shows as the fill when the “Apply to selection” button is clicked

#### C. Prefix styles with... (⚠️ Need to delete the styles created beforehand in Figma)
✅  `first-theme/1-color-token` shows as the fill when the color token ⚫ is clicked
✅  `first-theme/1-color-token` shows as the fill when the “Apply to selection” button is clicked

#### B & C  (⚠️ Need to delete the styles created beforehand in Figma)
✅  `first-theme/1-color-token` shows as the fill when the color token ⚫ is clicked
✅ `first-theme/1-color-token` shows as the fill when the “Apply to selection” button is clicked

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/setNodeData.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export const setNodeData: AsyncMessageChannelHandlers[AsyncMessageTypes.SET_NODE
         variableReferences: figmaVariableReferences,
         styleReferences: figmaStyleReferences,
         stylePathPrefix,
-        ignoreFirstPartForStyles: msg.settings.prefixStylesWithThemeName,
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/setNodeData.ts:23]: Phew, good catch 😁

**Review by six7 — APPROVED** [review]
