### PR TITLE
Fix number tokens display in json

### LINKED ISSUE #3465: Number Tokens are Incorrectly Saved as Strings When Created via the Plugin
**Describe the bug**
When a number token is created using the plugin, it is incorrectly saved as a ⁠string in the JSON output `⁠"value": "16"`. According to the (DTCG) specification, number tokens should be stored as ⁠number types `"value": 16`. If a token is however manually added to the JSON file without quotation marks, the system correctly interprets it as a number. 

**To Reproduce**

**Expected behavior**
Number tokens need to be stored and pushed as `Numbers` and not as `Strings`

**Screenshots or Screencasts**
Creating number tokens within the plugin:
Image

Adding them via the JSON:
Image

### PR DESCRIPTION
**Pull request by akshay-gupta7**
### Why does this PR exist?

Closes #3465 

### What does this pull request do?

Currently number tokens are displayed as strings in the json file export/editor
According to DTCG format, it should be displayed in numeric format without quotes, this PR addresses that concern and will now be displayed with appropriate format.

### Testing this change

- Create a numeric token
- Go to JSON editor and check how is it being displayed

### Additional Notes (if any)

Screenshot 2025-07-31 at 11 55 52 AM

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/utils/trimValue.ts [hunk 1]
```diff
@@ -1,16 +1,40 @@
...
+      if (/^-?\d*\.?\d+$/.test(trimmedValue)) {
+        return numericValue;
+      }
+    }
+    return trimmedValue;
+  }
+
+  return value as string;
+}
+
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/utils/trimValue.ts]: move to its own file, add a test

File: packages/tokens-studio-for-figma/src/utils/trimValue.ts [hunk 2]
```diff
@@ -1,16 +1,40 @@
...
+export function processNumberValue(value: SingleToken['value']): number | string {
+  if (typeof value === 'number') {
+    return value;
+  }
+
+  if (typeof value === 'string') {
+    const trimmedValue = value.trim();
+    const numericValue = Number(trimmedValue);
+    if (!isNaN(numericValue) && isFinite(numericValue) && trimmedValue !== '') {
+      if (/^-?\d*\.?\d+$/.test(trimmedValue)) {
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/utils/trimValue.ts]: add a comment what this does

File: packages/tokens-studio-for-figma/src/utils/trimValue.test.ts [hunk 3]
```diff
@@ -71,4 +72,57 @@ describe('trimValue', () => {
...
+      expect(processNumberValue(' hello ')).toBe('hello');
+      expect(processNumberValue('abc')).toBe('abc');
+      expect(processNumberValue('')).toBe('');
+    });
+
+    it('should return trimmed string for invalid numbers', () => {
+      expect(processNumberValue('NaN')).toBe('NaN');
+      expect(processNumberValue('Infinity')).toBe('Infinity');
+    });
+  });
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/utils/trimValue.test.ts]: move to its own test file

File: packages/tokens-studio-for-figma/src/utils/trimValue.ts (hunk 2 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/utils/trimValue.ts]: added in [62e6e1d](https://github.com/tokens-studio/figma-plugin/pull/3477/commits/62e6e1db7dc338b0a2c7f3cf1f37bb8e7594b41f)

File: packages/tokens-studio-for-figma/src/utils/trimValue.test.ts (hunk 3 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/utils/trimValue.test.ts]: addressed in [107b17b](https://github.com/tokens-studio/figma-plugin/pull/3477/commits/107b17b0cc0a9d9e08e0055f909550a82ce97f7f)

File: packages/tokens-studio-for-figma/src/utils/trimValue.ts (hunk 1 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/utils/trimValue.ts]: addressed in [107b17b](https://github.com/tokens-studio/figma-plugin/pull/3477/commits/107b17b0cc0a9d9e08e0055f909550a82ce97f7f)
