### PR TITLE
2956 plugin crash when no unit on dimension token

### LINKED ISSUE #2956: Plugin crash when no unit on dimension token
**Describe the bug**

Plugin crashes when no unit is specified on a dimension token

**To Reproduce**

1. Create a dimension token
2. Do not add a unit
3. Edit the title to reset the error state
4. Click on the `Create` button

The plugin goes totally blank and you must restart to get it working again.

The token was not created

**Expected behavior**

Should not crash and token should be created

**Screenshots or Screencasts**

### PR DESCRIPTION
**Pull request by robinhoodie0823**
### Why does this PR exist?
Current plugin has in-correct error handling when token name changes. It reset error if name is changed, not token value.

Closes #2956  

### What does this pull request do?
Updated logic to check validation of token when name changes.

### Additional Notes (if any)

https://github.com/tokens-studio/figma-plugin/assets/103296157/ea347b7e-302f-4ddc-aa66-6d2444544467

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx [hunk 1]
```diff
@@ -183,12 +183,14 @@ function EditTokenForm({ resolvedTokens }: Props) {
 
   const handleNameChange = React.useCallback<React.ChangeEventHandler<HTMLInputElement>>(
     (e) => {
-      setError(null);
       if (internalEditToken) {
+        if (internalEditToken.type === TokenTypes.DIMENSION && isValidDimensionToken) {
+          setError(null);
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx:188]: The error persists even if the **Dimension** input is empty. 

Should this be reset somewhere else when it's empty?

File: packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx [hunk 2]
```diff
@@ -508,6 +508,11 @@ function EditTokenForm({ resolvedTokens }: Props) {
     }
   }, [dispatch, isValid, internalEditToken, submitTokenValue, isValidDimensionToken]);
 
+  const handleFormSubmit = React.useCallback((e: React.FormEvent<HTMLFormElement>) => {
+    e.preventDefault();
+    checkAndSubmitTokenValue?.();
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx:513]: why the `?.()` ?

**Review by six7 — APPROVED** [review]
