### PR TITLE
Fix styling issues post 2.0 release

### LINKED ISSUE #3083: Styles Issues after 2.0 release
**Describe the bug**
1. Issue where styles worked in 1.38.9, but after release they didn't. (screenrecording Robbert > can't share the recording over here) > @keeganedwin can you link related thread?
2. Issue where multiple themes are enabled and the styles don't show in Figma. (screenrecording Keegan > can't share here) > https://tokens-studio.slack.com/archives/C02HN88QARL/p1723732865563299
Internal screenrecording: https://hyma-team.slack.com/archives/C04V8U8UH0F/p1723817105349809?thread_ts=1723813528.996869&cid=C04V8U8UH0F
3. #3088 
4. https://github.com/tokens-studio/figma-plugin/issues/3095

Also linking this user submitted related issue: https://github.com/tokens-studio/figma-plugin/issues/3080
https://github.com/tokens-studio/figma-plugin/issues/3088#issue-2475404043

### PR DESCRIPTION
**Pull request by akshay-gupta7**
Addresses #3088 - the themes that are now selected in the styles export modal shall be exported as styles.
Resolves #3083  - the 2nd point when multiple themes are enabled, then the styles don't show in Figma

# Description

- When we select the themes in the export modal to be exported as styles, the expectation now would be to export those themes regardless of their active/inactive status.
- When multiple themes are enabled, especially core/global, figma ceased to display the corresponding style token applied. This PR should address that

## Type of change

* [x] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update
* [ ] None of the above

# How to test this

1st Issue:

* Create some themes in the plugin.
* Keep them inactive.
* Go to Export Styles&Variables, choose the themes you wish to be exported as styles
* They should be exported irrespective of them being inactive

2nd Issue:

- Create some themes, along with a core/global theme
- Apply light/dark theme, theme switching should work fine, along with the correct styles being applied(and displayed on Figma) without core theme enabled
- As soon you apply core theme, the theme switching should work fine between light/dark or any other themes, along with the pertinent styles being showed in Figma

# Screenshots or video (if necessary):

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/store/useTokens.tsx [hunk 1]
```diff
@@ -433,58 +434,54 @@ export default function useTokens() {
...
-          if (!acc.find((token) => curr.name === token.name)) {
-            acc.push(curr);
-          }
+        const enabledTokenSets = Object.keys(selectedSets)
+          .filter((key) => selectedSets[key] === TokenSetStatus.ENABLED)
+          .map((tokenSet) => tokenSet);
+
+        if (enabledTokenSets.length === 0) {
+          notifyToUI(`No styles created for theme: ${selectedTheme.name}. Make sure some sets are enabled.`, { error: true });
+          continue;
```
Comment (akshay-gupta7) [inline packages/tokens-studio-for-figma/src/app/store/useTokens.tsx:454]: will remove this conitnue statement and optimize the code without it

**Comment by rbosker** [comment]
these fixes work for me upon testing

File: packages/tokens-studio-for-figma/src/app/store/useTokens.tsx [hunk 2]
```diff
@@ -433,58 +433,56 @@ export default function useTokens() {
...
+            const createStylesResult = await wrapTransaction({ name: 'createStyles' }, async () => AsyncMessageChannel.ReactInstance.message({
+              type: AsyncMessageTypes.CREATE_STYLES,
+              tokens: tokensToCreate,
+              settings,
+              selectedTheme,
+            }));
+
+            dispatch.tokenState.assignStyleIdsToCurrentTheme({ styleIds: createStylesResult.styleIds, tokens: tokensToCreate, selectedThemes });
+          } else {
+            notifyToUI(`No styles created for theme: ${selectedTheme.name}. Make sure some sets are enabled.`, { error: true });
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/store/useTokens.tsx:482]: Good one for adding some more details on the error message 😄

File: packages/tokens-studio-for-figma/src/app/store/useTokens.tsx [hunk 3]
```diff
@@ -433,58 +433,56 @@ export default function useTokens() {
...
-          settings.stylesEffect && curr.type === TokenTypes.BOX_SHADOW,
-        ].some((isEnabled) => isEnabled);
-        if (shouldCreate) {
-          if (!acc.find((token) => curr.name === token.name)) {
-            acc.push(curr);
-          }
-        }
-        return acc;
-      }, []);
+          const enabledTokenSets = Object.keys(selectedSets)
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/store/useTokens.tsx:447]: Should `selectedSets` have a fallback value, in case it's `undefined` and hence error out in here?

**Review by cuserox — APPROVED** [review]
Seems to fix the original issues ✨

File: packages/tokens-studio-for-figma/src/app/store/useTokens.tsx (hunk 3 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/app/store/useTokens.tsx:447]: @cuserox when the selected sets is empty, it will display the same message to the user, as for empty enabledTokenSets:
"No styles created for theme ......"

File: packages/tokens-studio-for-figma/src/app/store/useTokens.tsx (hunk 2 above)
Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/app/store/useTokens.tsx:482]: Thanks 🙌🏻

**Review by six7 — APPROVED** [review]

**Comment by moerthgeorg** [comment]
Thank you so much! Just tested it and it works for me again now. Great work!
