### PR TITLE
Fix stuck load-bar when token sets are empty whilst creating styles

### LINKED ISSUE #2896: 2.0: Style creation can become stuck if theme only has `references` and no active token sets
When creating styles we end up in a endless loading state when sets used in the themes are not active but disabled or reference only.

To reproduce:
- Create new file
- Create a token
- Create a theme group called `Theme / Default` or anything
- Set the token set to `disabled` or `reference only`
- Proceed to create styles (it's enough to leave one of the styles checkboxes active)

Expected: Do not get stuck on style creation
Actual: Style creation spinner goes on forever

Bonus: Can we adjust the error message if the reason for it was not that no themes were active but that inside there weren't any sets active? `No styles created. Make sure some sets are active`

Image

### PR DESCRIPTION
**Pull request by akshay-gupta7**
Resolves #2896 
Screenshot 2024-07-02 at 22 59 14

### CODE REVIEW

**Review by cuserox — APPROVED** [review]
Nice!

File: packages/tokens-studio-for-figma/src/app/store/useTokens.tsx [hunk 1]
```diff
@@ -398,10 +393,15 @@ export default function useTokens() {
...
-      notifyToUI('No styles created. Make sure themes are active.', { error: true });
+      notifyToUI('No styles created. Make sure some sets are active.', { error: true });
       return;
     }
 
+    dispatch.uiState.startJob({
+      name: BackgroundJobs.UI_CREATE_STYLES,
+      isInfinite: true,
+    });
+
```
Comment (akshay-gupta7) [inline packages/tokens-studio-for-figma/src/app/store/useTokens.tsx]: @robinhoodie0823 , this is the only change I made in useTokens.ts, I switched the order of the check and the start job, and made a change in the text displayed.
The other commit is just a linting update, you can get get those changes by running lint command
