### PR TITLE
Fix base font size display in settings

### LINKED ISSUE #2845: No UI Indication of The Base Font-size Not Actually Being 1rem
**Describe the bug**
The recording shows a token applied as a base font-size that is not being displayed unless you click the “change” button. There’s no indication in the UI that the base font size is not actually 1rem.

**To Reproduce**
1. Create a `base.fontSize` token in the font size type with a rem value
2. Reference this token as the Base font size in the `Settings` tab
3. Save

**Expected behavior**
base font-size should be displayed once referenced in the `Settings` tab

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/78895d1d-2c44-4bdf-9e1d-0d073d340eb1

### PR DESCRIPTION
**Pull request by akshay-gupta7**
- When a user changes the base font size from settings, either directly or via a font size token, the rem value will now be displayed in the settings with the current base font size(Default being 1 rem)

Closes #2845

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/RemConfiguration.tsx [hunk 1]
```diff
@@ -31,15 +27,30 @@ const RemConfiguration = () => {
...
+  const displayBaseFontValue = React.useMemo(() => {
+    const resolvedAliasBaseFontSize = getAliasValue(aliasBaseFontSize, resolvedTokens);
+
+    if (typeof resolvedAliasBaseFontSize === 'string' || typeof resolvedAliasBaseFontSize === 'number') {
+      const remValue =
+        typeof resolvedAliasBaseFontSize === 'number'
+          ? resolvedAliasBaseFontSize / 16
+          : parseFloat(resolvedAliasBaseFontSize) / 16;
+      const formattedRemValue = isNaN(remValue) ? 1 : Number(remValue.toFixed(2));
+      return `${t('baseFont')} (${formattedRemValue} rem)`;
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/app/components/RemConfiguration.tsx:49]: the calculation you have here is for outputting `rem`.

i'd say lets output `px` instead, because that field really lets the user define the value of `1rem`. so `1rem` doesnt ever change, its just the value it has.

for example

`1rem = 16px` (default)
`1rem = 20px` (base font size token = 20px)

so instead of displaying `(1.5rem)` here, lets show `(16px)` or `(20px)` here and in the outer settings page

CleanShot 2024-06-15 at 11 32 41@2x

File: packages/tokens-studio-for-figma/src/i18n/lang/en/settings.json [hunk 2]
```diff
@@ -6,7 +6,7 @@
   "confirm": "Confirm",
   "storeTokenId": "Store IDs on storage",
   "storeTokenIdExplanation": "Automatically generate unique IDs for your tokens for tracking.",
-  "baseFont": "Base font size (1rem)",
+  "baseFont": "Base font size",
```
Comment (six7) [inline packages/tokens-studio-for-figma/src/i18n/lang/en/settings.json:9]: can you also make these changes in the other languages?

Comment (akshay-gupta7) [reply packages/tokens-studio-for-figma/src/i18n/lang/en/settings.json:9]: Other languages already don't include the 1rem

**Review by six7 — APPROVED** [review]
