### PR TITLE
Revert github pull to large modal with css fixes

### LINKED ISSUE #2980: Pull from Git Modal should get `size=large`
The Pull from Git modal currently uses a `size=full` which causes it to look weird as it takes up the full size.

Let's change it to `size="large"` so it looks like a proper modal

Image

### PR DESCRIPTION
**Pull request by macintoshhelper**
### Why does this PR exist?

Fixes #2980 

### What does this pull request do?

- Reverts GitHub pull modal to `large` instead of `fullscreen`
- Fixes some CSS issues (width overflow and word break), related to less available screen real estate

### Testing this change

- Setup a GitHub repo
- Sync tokens to the GitHub repo
- Make changes (i.e. rename the set names)
- Click the `Pull From GitHub` button in the bottom footer bar

### Additional Notes (if any)

image

image

image

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/ChangedTokenItem.tsx [hunk 1]
```diff
@@ -15,12 +15,12 @@ export default function ChangedTokenItem({
   return (
     <Stack direction="row" justify="between" css={{ padding: '$2 0' }}>
       <Stack direction={token.importType === 'REMOVE' ? 'row' : 'column'} gap={1} justify="between" css={{ width: '100%' }}>
-        <Text bold size="small">{token.name}</Text>
+        <Text bold size="small" css={{ wordBreak: 'break-word' }}>{token.name}</Text>
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/ChangedTokenItem.tsx:18]: Perhaps we can add a small margin at the bottom, for when the name is very long and wraps

File: packages/tokens-studio-for-figma/src/app/components/ChangedStateList.tsx [hunk 2]
```diff
@@ -31,7 +31,7 @@ function ChangedStateList() {
   return (
     <Stack direction="column" gap={1} css={{ padding: '$4' }}>
       {Object.entries(changedState.tokens).length > 0 && Object.entries(changedState.tokens)?.map(([tokenSet, tokenList]) => (
-        <Box key={tokenSet}>
+        <Box key={tokenSet} css={{ maxWidth: '100%' }}>
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/ChangedStateList.tsx:34]: Is this _really_ needed? Seems to take up the full space anyway 👀

**Review by cuserox — APPROVED** [review]
A couple of suggestions, looks good!

File: packages/tokens-studio-for-figma/src/app/components/ChangedTokenItem.tsx (hunk 1 above)
Comment (macintoshhelper) [reply packages/tokens-studio-for-figma/src/app/components/ChangedTokenItem.tsx:18]: The typography margins in other parts of this pull modal component could do with some improvements also. It would be good to work on a table view in ds for this kind of UI.
