### PR TITLE
Revert manage theme followup

### LINKED ISSUE #2900: Unable to Close Manage Themes Modal After Making Edits
**Describe the bug**
This bug is not easily reproducible but 2 users so far have raised the issue, one raised the issue after using `rc8`. The bug is also present in `38.9`.

**To Reproduce**
It is a bit unclear as to what steps are carried out that causes the plugin to free in this (manage themes) state, but a prolonged period of editing/making changes and then trying to close the modal seems to be the issue.

**Use-case:**
I was doing is pretty mundane adding/editing/deleting of themes. Even when I completely delete all themes (in an attempt to start over from scratch), the modal won’t close.

**Expected behavior**
Manage themes modal should just close regardless of the amount of time a user spends editing themes.

**Screenshots or Screencasts**
Screenshot 2024-06-14 at 9 11 28 AM

### PR DESCRIPTION
**Pull request by macintoshhelper**
### Why does this PR exist?

Resolve comments in #2883 
Closes #2900

### What does this pull request do?

- Add locales for manage themes
- Remove redundant button styling for manage themes
- Fixes close button being blocked after editing group name
- Adds UI for confirm/cancel buttons while renaming theme group name

### Testing this change

1. Click `Theme: <Theme Name>` then `Manage themes >`
2. Try renaming a group and press `Esc` and confirm that the modal isn't closed
3. Try renaming a group and check that the `Cancel` and `Confirm` buttons work correctly
4. Click through into a theme, click the group name and click `Create new group`
5. Confirm that pressing `Esc` doesn't close the modal
6. Check that all locales are showing/resolving properly
7. In the main modal screen, click to rename a group and confirm that the modal `Close` button works correctly and isn't blocked

### Additional Notes (if any)

**After**

image

### CODE REVIEW

File: packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx [hunk 1]
```diff
@@ -146,9 +148,8 @@ export const CreateOrEditThemeForm: React.FC<React.PropsWithChildren<React.Props
                       icon={<IconPlus />}
                       onClick={handleAddGroup}
                       size="small"
-                      css={{ display: 'flex', alignItems: 'center', height: '28px' }}
                     >
-                      Add&nbsp;group
+                      {t('addGroup')}
```
Comment (macintoshhelper) [inline packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx:152]: The `&nbsp;` seems to be unnecessary, and feels like an antipattern to use HTML characters in locale files. Tried resizing the plugin to minimum width and the button stayed on one line.

Comment (six7) [reply packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx:161]: agree should also be solveable with css

**Review by six7 — APPROVED** [review]
just one small comment in slack

File: packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx [hunk 2]
```diff
@@ -237,7 +237,6 @@ export const ManageThemesModal: React.FC<React.PropsWithChildren<React.PropsWith
                     <ThemeListGroupHeader
                       label={item.value === INTERNAL_THEMES_NO_GROUP ? INTERNAL_THEMES_NO_GROUP_LABEL : item.value as string}
                       groupName={item.value as string}
-                      setIsGroupEditing={handleUpdateIsEditing}
```
Comment (cuserox) [inline packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/ManageThemesModal.tsx:240]: Can remove `handleUpdateIsEditing` and the state related to `handleUpdateIsEditing` above as it's not used.

File: packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx [hunk 3]
```diff
@@ -117,7 +127,8 @@ export const CreateOrEditThemeForm: React.FC<React.PropsWithChildren<React.Props
                 autofocus
                 data-testid="create-or-edit-theme-form--group--name"
                 {...register('group')}
-                placeholder="Add group"
+                placeholder={t('addGroup')}
+                onKeyDown={handleKeyDown('group')}
```
[the remark this answers is not in the document]
Comment (macintoshhelper) [reply packages/tokens-studio-for-figma/src/app/components/ManageThemesModal/CreateOrEditThemeForm.tsx]: Changed the function `handleKeyDown` to `handleGroupKeyDown`, the `'group'` argument here is redundant since the function is only being used in one place.
